import { writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { buildPaletteVars } from './palette-generation.mjs'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')
const OUTPUT_PATH = resolve(ROOT, 'src/theme/runtime-palette.generated.ts')

type PaletteMode = 'light' | 'dark'

function quoteString(value: string) {
  return `'${value.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`
}

function formatPaletteMode(mode: PaletteMode, vars: Record<string, string>) {
  const entries = Object.entries(vars).map(([key, value]) => `    ${quoteString(key)}: ${quoteString(value)},`)
  return [`  ${mode}: {`, ...entries, '  },'].join('\n')
}

const generated = `// Auto-generated by scripts/generate-runtime-palette-source.ts
// Do not edit by hand.

export const runtimePaletteVarsByMode = {
${formatPaletteMode('light', buildPaletteVars('light'))}
${formatPaletteMode('dark', buildPaletteVars('dark'))}
} as const
`

writeFileSync(OUTPUT_PATH, generated)
console.log(`Updated ${OUTPUT_PATH}`)
