import { writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { CHART_COLOR_KEYS, type ChartColorToken } from '@incmix/theme'
import {
  chartDarkContrastTokenMap,
  chartDarkTokenColorMap,
  chartLightContrastTokenMap,
  chartLightTokenColorMap,
} from '../src/theme/chart-token-map.ts'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')
const CSS_PATH = resolve(ROOT, 'src/theme/chart-tokens.css')

function chartVariableName(color: ChartColorToken): string {
  return `--chart-${color.slice('chart'.length)}`
}

function renderDeclarations(
  colorMap: Record<ChartColorToken, string>,
  contrastMap: Record<ChartColorToken, string>,
): string {
  return CHART_COLOR_KEYS.flatMap(color => [
    `  ${chartVariableName(color)}: ${colorMap[color]};`,
    `  ${chartVariableName(color)}-contrast: ${contrastMap[color]};`,
  ]).join('\n')
}

function main() {
  const css = `/* This file is generated by scripts/generate-chart-tokens-css.ts. */

:root,
.af-themes {
${renderDeclarations(chartLightTokenColorMap, chartLightContrastTokenMap)}
}

.dark,
.af-themes.dark {
${renderDeclarations(chartDarkTokenColorMap, chartDarkContrastTokenMap)}
}
`

  writeFileSync(CSS_PATH, css)
  console.log(`Updated ${CSS_PATH}`)
}

main()
