/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteRouteImport } from './routes/docs/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsVanillaExtractRouteImport } from './routes/docs/vanilla-extract'
import { Route as DocsTokenGridRouteImport } from './routes/docs/token-grid'
import { Route as DocsThemingRouteImport } from './routes/docs/theming'
import { Route as DocsPreviewRouteImport } from './routes/docs/preview'
import { Route as DocsContainerQueriesRouteImport } from './routes/docs/container-queries'
import { Route as DocsCompositesRouteImport } from './routes/docs/composites'
import { Route as DocsChartsRouteImport } from './routes/docs/charts'
import { Route as DocsAutoformRouteImport } from './routes/docs/autoform'
import { Route as DocsViewsOverviewRouteImport } from './routes/docs/views/overview'
import { Route as DocsTypographySlugRouteImport } from './routes/docs/typography/$slug'
import { Route as DocsThemeGradientRouteImport } from './routes/docs/theme/gradient'
import { Route as DocsThemeColorRouteImport } from './routes/docs/theme/color'
import { Route as DocsMediaVideoRouteImport } from './routes/docs/media/video'
import { Route as DocsMediaMediaPlayerRouteImport } from './routes/docs/media/media-player'
import { Route as DocsLayoutsSlugRouteImport } from './routes/docs/layouts/$slug'
import { Route as DocsFormSlugRouteImport } from './routes/docs/form/$slug'
import { Route as DocsElementsSlugRouteImport } from './routes/docs/elements/$slug'
import { Route as DocsDeclarativeRegistryRouteImport } from './routes/docs/declarative/registry'
import { Route as DocsDeclarativeGrammarRouteImport } from './routes/docs/declarative/grammar'
import { Route as DocsAutoformSchemaContractRouteImport } from './routes/docs/autoform/schema-contract'
import { Route as DocsAutoformSchemaAstRouteImport } from './routes/docs/autoform/schema-ast'
import { Route as DocsAutoformRuntimeRouteImport } from './routes/docs/autoform/runtime'
import { Route as DocsAutoformRendererRouteImport } from './routes/docs/autoform/renderer'
import { Route as DocsAutoformE2eRouteImport } from './routes/docs/autoform/e2e'
import { Route as DocsAutoformAuditRouteImport } from './routes/docs/autoform/audit'
import { Route as DocsApiWrappersSlugRouteImport } from './routes/docs/api/wrappers/$slug'

const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsVanillaExtractRoute = DocsVanillaExtractRouteImport.update({
  id: '/vanilla-extract',
  path: '/vanilla-extract',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsTokenGridRoute = DocsTokenGridRouteImport.update({
  id: '/token-grid',
  path: '/token-grid',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsThemingRoute = DocsThemingRouteImport.update({
  id: '/theming',
  path: '/theming',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsPreviewRoute = DocsPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsContainerQueriesRoute = DocsContainerQueriesRouteImport.update({
  id: '/container-queries',
  path: '/container-queries',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsCompositesRoute = DocsCompositesRouteImport.update({
  id: '/composites',
  path: '/composites',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsChartsRoute = DocsChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsAutoformRoute = DocsAutoformRouteImport.update({
  id: '/autoform',
  path: '/autoform',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsViewsOverviewRoute = DocsViewsOverviewRouteImport.update({
  id: '/views/overview',
  path: '/views/overview',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsTypographySlugRoute = DocsTypographySlugRouteImport.update({
  id: '/typography/$slug',
  path: '/typography/$slug',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsThemeGradientRoute = DocsThemeGradientRouteImport.update({
  id: '/theme/gradient',
  path: '/theme/gradient',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsThemeColorRoute = DocsThemeColorRouteImport.update({
  id: '/theme/color',
  path: '/theme/color',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsMediaVideoRoute = DocsMediaVideoRouteImport.update({
  id: '/media/video',
  path: '/media/video',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsMediaMediaPlayerRoute = DocsMediaMediaPlayerRouteImport.update({
  id: '/media/media-player',
  path: '/media/media-player',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsLayoutsSlugRoute = DocsLayoutsSlugRouteImport.update({
  id: '/layouts/$slug',
  path: '/layouts/$slug',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsFormSlugRoute = DocsFormSlugRouteImport.update({
  id: '/form/$slug',
  path: '/form/$slug',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsElementsSlugRoute = DocsElementsSlugRouteImport.update({
  id: '/elements/$slug',
  path: '/elements/$slug',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsDeclarativeRegistryRoute = DocsDeclarativeRegistryRouteImport.update({
  id: '/declarative/registry',
  path: '/declarative/registry',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsDeclarativeGrammarRoute = DocsDeclarativeGrammarRouteImport.update({
  id: '/declarative/grammar',
  path: '/declarative/grammar',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsAutoformSchemaContractRoute =
  DocsAutoformSchemaContractRouteImport.update({
    id: '/schema-contract',
    path: '/schema-contract',
    getParentRoute: () => DocsAutoformRoute,
  } as any)
const DocsAutoformSchemaAstRoute = DocsAutoformSchemaAstRouteImport.update({
  id: '/schema-ast',
  path: '/schema-ast',
  getParentRoute: () => DocsAutoformRoute,
} as any)
const DocsAutoformRuntimeRoute = DocsAutoformRuntimeRouteImport.update({
  id: '/runtime',
  path: '/runtime',
  getParentRoute: () => DocsAutoformRoute,
} as any)
const DocsAutoformRendererRoute = DocsAutoformRendererRouteImport.update({
  id: '/renderer',
  path: '/renderer',
  getParentRoute: () => DocsAutoformRoute,
} as any)
const DocsAutoformE2eRoute = DocsAutoformE2eRouteImport.update({
  id: '/e2e',
  path: '/e2e',
  getParentRoute: () => DocsAutoformRoute,
} as any)
const DocsAutoformAuditRoute = DocsAutoformAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DocsAutoformRoute,
} as any)
const DocsApiWrappersSlugRoute = DocsApiWrappersSlugRouteImport.update({
  id: '/api/wrappers/$slug',
  path: '/api/wrappers/$slug',
  getParentRoute: () => DocsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/docs/autoform': typeof DocsAutoformRouteWithChildren
  '/docs/charts': typeof DocsChartsRoute
  '/docs/composites': typeof DocsCompositesRoute
  '/docs/container-queries': typeof DocsContainerQueriesRoute
  '/docs/preview': typeof DocsPreviewRoute
  '/docs/theming': typeof DocsThemingRoute
  '/docs/token-grid': typeof DocsTokenGridRoute
  '/docs/vanilla-extract': typeof DocsVanillaExtractRoute
  '/docs/autoform/audit': typeof DocsAutoformAuditRoute
  '/docs/autoform/e2e': typeof DocsAutoformE2eRoute
  '/docs/autoform/renderer': typeof DocsAutoformRendererRoute
  '/docs/autoform/runtime': typeof DocsAutoformRuntimeRoute
  '/docs/autoform/schema-ast': typeof DocsAutoformSchemaAstRoute
  '/docs/autoform/schema-contract': typeof DocsAutoformSchemaContractRoute
  '/docs/declarative/grammar': typeof DocsDeclarativeGrammarRoute
  '/docs/declarative/registry': typeof DocsDeclarativeRegistryRoute
  '/docs/elements/$slug': typeof DocsElementsSlugRoute
  '/docs/form/$slug': typeof DocsFormSlugRoute
  '/docs/layouts/$slug': typeof DocsLayoutsSlugRoute
  '/docs/media/media-player': typeof DocsMediaMediaPlayerRoute
  '/docs/media/video': typeof DocsMediaVideoRoute
  '/docs/theme/color': typeof DocsThemeColorRoute
  '/docs/theme/gradient': typeof DocsThemeGradientRoute
  '/docs/typography/$slug': typeof DocsTypographySlugRoute
  '/docs/views/overview': typeof DocsViewsOverviewRoute
  '/docs/api/wrappers/$slug': typeof DocsApiWrappersSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/docs/autoform': typeof DocsAutoformRouteWithChildren
  '/docs/charts': typeof DocsChartsRoute
  '/docs/composites': typeof DocsCompositesRoute
  '/docs/container-queries': typeof DocsContainerQueriesRoute
  '/docs/preview': typeof DocsPreviewRoute
  '/docs/theming': typeof DocsThemingRoute
  '/docs/token-grid': typeof DocsTokenGridRoute
  '/docs/vanilla-extract': typeof DocsVanillaExtractRoute
  '/docs/autoform/audit': typeof DocsAutoformAuditRoute
  '/docs/autoform/e2e': typeof DocsAutoformE2eRoute
  '/docs/autoform/renderer': typeof DocsAutoformRendererRoute
  '/docs/autoform/runtime': typeof DocsAutoformRuntimeRoute
  '/docs/autoform/schema-ast': typeof DocsAutoformSchemaAstRoute
  '/docs/autoform/schema-contract': typeof DocsAutoformSchemaContractRoute
  '/docs/declarative/grammar': typeof DocsDeclarativeGrammarRoute
  '/docs/declarative/registry': typeof DocsDeclarativeRegistryRoute
  '/docs/elements/$slug': typeof DocsElementsSlugRoute
  '/docs/form/$slug': typeof DocsFormSlugRoute
  '/docs/layouts/$slug': typeof DocsLayoutsSlugRoute
  '/docs/media/media-player': typeof DocsMediaMediaPlayerRoute
  '/docs/media/video': typeof DocsMediaVideoRoute
  '/docs/theme/color': typeof DocsThemeColorRoute
  '/docs/theme/gradient': typeof DocsThemeGradientRoute
  '/docs/typography/$slug': typeof DocsTypographySlugRoute
  '/docs/views/overview': typeof DocsViewsOverviewRoute
  '/docs/api/wrappers/$slug': typeof DocsApiWrappersSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/docs/autoform': typeof DocsAutoformRouteWithChildren
  '/docs/charts': typeof DocsChartsRoute
  '/docs/composites': typeof DocsCompositesRoute
  '/docs/container-queries': typeof DocsContainerQueriesRoute
  '/docs/preview': typeof DocsPreviewRoute
  '/docs/theming': typeof DocsThemingRoute
  '/docs/token-grid': typeof DocsTokenGridRoute
  '/docs/vanilla-extract': typeof DocsVanillaExtractRoute
  '/docs/autoform/audit': typeof DocsAutoformAuditRoute
  '/docs/autoform/e2e': typeof DocsAutoformE2eRoute
  '/docs/autoform/renderer': typeof DocsAutoformRendererRoute
  '/docs/autoform/runtime': typeof DocsAutoformRuntimeRoute
  '/docs/autoform/schema-ast': typeof DocsAutoformSchemaAstRoute
  '/docs/autoform/schema-contract': typeof DocsAutoformSchemaContractRoute
  '/docs/declarative/grammar': typeof DocsDeclarativeGrammarRoute
  '/docs/declarative/registry': typeof DocsDeclarativeRegistryRoute
  '/docs/elements/$slug': typeof DocsElementsSlugRoute
  '/docs/form/$slug': typeof DocsFormSlugRoute
  '/docs/layouts/$slug': typeof DocsLayoutsSlugRoute
  '/docs/media/media-player': typeof DocsMediaMediaPlayerRoute
  '/docs/media/video': typeof DocsMediaVideoRoute
  '/docs/theme/color': typeof DocsThemeColorRoute
  '/docs/theme/gradient': typeof DocsThemeGradientRoute
  '/docs/typography/$slug': typeof DocsTypographySlugRoute
  '/docs/views/overview': typeof DocsViewsOverviewRoute
  '/docs/api/wrappers/$slug': typeof DocsApiWrappersSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/docs/autoform'
    | '/docs/charts'
    | '/docs/composites'
    | '/docs/container-queries'
    | '/docs/preview'
    | '/docs/theming'
    | '/docs/token-grid'
    | '/docs/vanilla-extract'
    | '/docs/autoform/audit'
    | '/docs/autoform/e2e'
    | '/docs/autoform/renderer'
    | '/docs/autoform/runtime'
    | '/docs/autoform/schema-ast'
    | '/docs/autoform/schema-contract'
    | '/docs/declarative/grammar'
    | '/docs/declarative/registry'
    | '/docs/elements/$slug'
    | '/docs/form/$slug'
    | '/docs/layouts/$slug'
    | '/docs/media/media-player'
    | '/docs/media/video'
    | '/docs/theme/color'
    | '/docs/theme/gradient'
    | '/docs/typography/$slug'
    | '/docs/views/overview'
    | '/docs/api/wrappers/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/docs/autoform'
    | '/docs/charts'
    | '/docs/composites'
    | '/docs/container-queries'
    | '/docs/preview'
    | '/docs/theming'
    | '/docs/token-grid'
    | '/docs/vanilla-extract'
    | '/docs/autoform/audit'
    | '/docs/autoform/e2e'
    | '/docs/autoform/renderer'
    | '/docs/autoform/runtime'
    | '/docs/autoform/schema-ast'
    | '/docs/autoform/schema-contract'
    | '/docs/declarative/grammar'
    | '/docs/declarative/registry'
    | '/docs/elements/$slug'
    | '/docs/form/$slug'
    | '/docs/layouts/$slug'
    | '/docs/media/media-player'
    | '/docs/media/video'
    | '/docs/theme/color'
    | '/docs/theme/gradient'
    | '/docs/typography/$slug'
    | '/docs/views/overview'
    | '/docs/api/wrappers/$slug'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/docs/autoform'
    | '/docs/charts'
    | '/docs/composites'
    | '/docs/container-queries'
    | '/docs/preview'
    | '/docs/theming'
    | '/docs/token-grid'
    | '/docs/vanilla-extract'
    | '/docs/autoform/audit'
    | '/docs/autoform/e2e'
    | '/docs/autoform/renderer'
    | '/docs/autoform/runtime'
    | '/docs/autoform/schema-ast'
    | '/docs/autoform/schema-contract'
    | '/docs/declarative/grammar'
    | '/docs/declarative/registry'
    | '/docs/elements/$slug'
    | '/docs/form/$slug'
    | '/docs/layouts/$slug'
    | '/docs/media/media-player'
    | '/docs/media/video'
    | '/docs/theme/color'
    | '/docs/theme/gradient'
    | '/docs/typography/$slug'
    | '/docs/views/overview'
    | '/docs/api/wrappers/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/vanilla-extract': {
      id: '/docs/vanilla-extract'
      path: '/vanilla-extract'
      fullPath: '/docs/vanilla-extract'
      preLoaderRoute: typeof DocsVanillaExtractRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/token-grid': {
      id: '/docs/token-grid'
      path: '/token-grid'
      fullPath: '/docs/token-grid'
      preLoaderRoute: typeof DocsTokenGridRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/theming': {
      id: '/docs/theming'
      path: '/theming'
      fullPath: '/docs/theming'
      preLoaderRoute: typeof DocsThemingRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/preview': {
      id: '/docs/preview'
      path: '/preview'
      fullPath: '/docs/preview'
      preLoaderRoute: typeof DocsPreviewRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/container-queries': {
      id: '/docs/container-queries'
      path: '/container-queries'
      fullPath: '/docs/container-queries'
      preLoaderRoute: typeof DocsContainerQueriesRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/composites': {
      id: '/docs/composites'
      path: '/composites'
      fullPath: '/docs/composites'
      preLoaderRoute: typeof DocsCompositesRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/charts': {
      id: '/docs/charts'
      path: '/charts'
      fullPath: '/docs/charts'
      preLoaderRoute: typeof DocsChartsRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/autoform': {
      id: '/docs/autoform'
      path: '/autoform'
      fullPath: '/docs/autoform'
      preLoaderRoute: typeof DocsAutoformRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/views/overview': {
      id: '/docs/views/overview'
      path: '/views/overview'
      fullPath: '/docs/views/overview'
      preLoaderRoute: typeof DocsViewsOverviewRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/typography/$slug': {
      id: '/docs/typography/$slug'
      path: '/typography/$slug'
      fullPath: '/docs/typography/$slug'
      preLoaderRoute: typeof DocsTypographySlugRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/theme/gradient': {
      id: '/docs/theme/gradient'
      path: '/theme/gradient'
      fullPath: '/docs/theme/gradient'
      preLoaderRoute: typeof DocsThemeGradientRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/theme/color': {
      id: '/docs/theme/color'
      path: '/theme/color'
      fullPath: '/docs/theme/color'
      preLoaderRoute: typeof DocsThemeColorRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/media/video': {
      id: '/docs/media/video'
      path: '/media/video'
      fullPath: '/docs/media/video'
      preLoaderRoute: typeof DocsMediaVideoRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/media/media-player': {
      id: '/docs/media/media-player'
      path: '/media/media-player'
      fullPath: '/docs/media/media-player'
      preLoaderRoute: typeof DocsMediaMediaPlayerRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/layouts/$slug': {
      id: '/docs/layouts/$slug'
      path: '/layouts/$slug'
      fullPath: '/docs/layouts/$slug'
      preLoaderRoute: typeof DocsLayoutsSlugRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/form/$slug': {
      id: '/docs/form/$slug'
      path: '/form/$slug'
      fullPath: '/docs/form/$slug'
      preLoaderRoute: typeof DocsFormSlugRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/elements/$slug': {
      id: '/docs/elements/$slug'
      path: '/elements/$slug'
      fullPath: '/docs/elements/$slug'
      preLoaderRoute: typeof DocsElementsSlugRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/declarative/registry': {
      id: '/docs/declarative/registry'
      path: '/declarative/registry'
      fullPath: '/docs/declarative/registry'
      preLoaderRoute: typeof DocsDeclarativeRegistryRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/declarative/grammar': {
      id: '/docs/declarative/grammar'
      path: '/declarative/grammar'
      fullPath: '/docs/declarative/grammar'
      preLoaderRoute: typeof DocsDeclarativeGrammarRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/autoform/schema-contract': {
      id: '/docs/autoform/schema-contract'
      path: '/schema-contract'
      fullPath: '/docs/autoform/schema-contract'
      preLoaderRoute: typeof DocsAutoformSchemaContractRouteImport
      parentRoute: typeof DocsAutoformRoute
    }
    '/docs/autoform/schema-ast': {
      id: '/docs/autoform/schema-ast'
      path: '/schema-ast'
      fullPath: '/docs/autoform/schema-ast'
      preLoaderRoute: typeof DocsAutoformSchemaAstRouteImport
      parentRoute: typeof DocsAutoformRoute
    }
    '/docs/autoform/runtime': {
      id: '/docs/autoform/runtime'
      path: '/runtime'
      fullPath: '/docs/autoform/runtime'
      preLoaderRoute: typeof DocsAutoformRuntimeRouteImport
      parentRoute: typeof DocsAutoformRoute
    }
    '/docs/autoform/renderer': {
      id: '/docs/autoform/renderer'
      path: '/renderer'
      fullPath: '/docs/autoform/renderer'
      preLoaderRoute: typeof DocsAutoformRendererRouteImport
      parentRoute: typeof DocsAutoformRoute
    }
    '/docs/autoform/e2e': {
      id: '/docs/autoform/e2e'
      path: '/e2e'
      fullPath: '/docs/autoform/e2e'
      preLoaderRoute: typeof DocsAutoformE2eRouteImport
      parentRoute: typeof DocsAutoformRoute
    }
    '/docs/autoform/audit': {
      id: '/docs/autoform/audit'
      path: '/audit'
      fullPath: '/docs/autoform/audit'
      preLoaderRoute: typeof DocsAutoformAuditRouteImport
      parentRoute: typeof DocsAutoformRoute
    }
    '/docs/api/wrappers/$slug': {
      id: '/docs/api/wrappers/$slug'
      path: '/api/wrappers/$slug'
      fullPath: '/docs/api/wrappers/$slug'
      preLoaderRoute: typeof DocsApiWrappersSlugRouteImport
      parentRoute: typeof DocsRouteRoute
    }
  }
}

interface DocsAutoformRouteChildren {
  DocsAutoformAuditRoute: typeof DocsAutoformAuditRoute
  DocsAutoformE2eRoute: typeof DocsAutoformE2eRoute
  DocsAutoformRendererRoute: typeof DocsAutoformRendererRoute
  DocsAutoformRuntimeRoute: typeof DocsAutoformRuntimeRoute
  DocsAutoformSchemaAstRoute: typeof DocsAutoformSchemaAstRoute
  DocsAutoformSchemaContractRoute: typeof DocsAutoformSchemaContractRoute
}

const DocsAutoformRouteChildren: DocsAutoformRouteChildren = {
  DocsAutoformAuditRoute: DocsAutoformAuditRoute,
  DocsAutoformE2eRoute: DocsAutoformE2eRoute,
  DocsAutoformRendererRoute: DocsAutoformRendererRoute,
  DocsAutoformRuntimeRoute: DocsAutoformRuntimeRoute,
  DocsAutoformSchemaAstRoute: DocsAutoformSchemaAstRoute,
  DocsAutoformSchemaContractRoute: DocsAutoformSchemaContractRoute,
}

const DocsAutoformRouteWithChildren = DocsAutoformRoute._addFileChildren(
  DocsAutoformRouteChildren,
)

interface DocsRouteRouteChildren {
  DocsAutoformRoute: typeof DocsAutoformRouteWithChildren
  DocsChartsRoute: typeof DocsChartsRoute
  DocsCompositesRoute: typeof DocsCompositesRoute
  DocsContainerQueriesRoute: typeof DocsContainerQueriesRoute
  DocsPreviewRoute: typeof DocsPreviewRoute
  DocsThemingRoute: typeof DocsThemingRoute
  DocsTokenGridRoute: typeof DocsTokenGridRoute
  DocsVanillaExtractRoute: typeof DocsVanillaExtractRoute
  DocsDeclarativeGrammarRoute: typeof DocsDeclarativeGrammarRoute
  DocsDeclarativeRegistryRoute: typeof DocsDeclarativeRegistryRoute
  DocsElementsSlugRoute: typeof DocsElementsSlugRoute
  DocsFormSlugRoute: typeof DocsFormSlugRoute
  DocsLayoutsSlugRoute: typeof DocsLayoutsSlugRoute
  DocsMediaMediaPlayerRoute: typeof DocsMediaMediaPlayerRoute
  DocsMediaVideoRoute: typeof DocsMediaVideoRoute
  DocsThemeColorRoute: typeof DocsThemeColorRoute
  DocsThemeGradientRoute: typeof DocsThemeGradientRoute
  DocsTypographySlugRoute: typeof DocsTypographySlugRoute
  DocsViewsOverviewRoute: typeof DocsViewsOverviewRoute
  DocsApiWrappersSlugRoute: typeof DocsApiWrappersSlugRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsAutoformRoute: DocsAutoformRouteWithChildren,
  DocsChartsRoute: DocsChartsRoute,
  DocsCompositesRoute: DocsCompositesRoute,
  DocsContainerQueriesRoute: DocsContainerQueriesRoute,
  DocsPreviewRoute: DocsPreviewRoute,
  DocsThemingRoute: DocsThemingRoute,
  DocsTokenGridRoute: DocsTokenGridRoute,
  DocsVanillaExtractRoute: DocsVanillaExtractRoute,
  DocsDeclarativeGrammarRoute: DocsDeclarativeGrammarRoute,
  DocsDeclarativeRegistryRoute: DocsDeclarativeRegistryRoute,
  DocsElementsSlugRoute: DocsElementsSlugRoute,
  DocsFormSlugRoute: DocsFormSlugRoute,
  DocsLayoutsSlugRoute: DocsLayoutsSlugRoute,
  DocsMediaMediaPlayerRoute: DocsMediaMediaPlayerRoute,
  DocsMediaVideoRoute: DocsMediaVideoRoute,
  DocsThemeColorRoute: DocsThemeColorRoute,
  DocsThemeGradientRoute: DocsThemeGradientRoute,
  DocsTypographySlugRoute: DocsTypographySlugRoute,
  DocsViewsOverviewRoute: DocsViewsOverviewRoute,
  DocsApiWrappersSlugRoute: DocsApiWrappersSlugRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRouteRoute: DocsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
