import type { DbDiagramDocument } from './types'

export const sampleDbSchemaDiagramDocument: DbDiagramDocument = {
  version: 1,
  id: 'commerce-schema',
  title: 'Commerce schema',
  dialect: 'postgresql',
  schemas: [{ id: 'public', name: 'public' }],
  extensions: [{ id: 'pgcrypto', name: 'pgcrypto' }],
  domains: [
    {
      id: 'email-address',
      schemaId: 'public',
      name: 'email_address',
      type: 'text',
      checks: [{ id: 'email_format', name: 'email_address_format_check', expression: "VALUE LIKE '%@%'" }],
    },
  ],
  types: [
    {
      id: 'shipping-address',
      schemaId: 'public',
      name: 'shipping_address',
      fields: [
        { id: 'line_1', name: 'line_1', type: 'varchar', length: 160, nullable: false },
        { id: 'city', name: 'city', type: 'varchar', length: 80, nullable: false },
        { id: 'postal_code', name: 'postal_code', type: 'varchar', length: 24, nullable: false },
        { id: 'country_code', name: 'country_code', type: 'char', length: 2, nullable: false },
      ],
    },
  ],
  enums: [
    {
      id: 'order-status',
      schemaId: 'public',
      name: 'order_status',
      values: ['pending', 'paid', 'shipped', 'cancelled'],
    },
  ],
  tables: [
    {
      id: 'users',
      schemaId: 'public',
      name: 'users',
      kind: 'dim',
      description: 'Customer identity and profile data',
      columns: [
        { id: 'id', name: 'id', type: 'uuid', primaryKey: true },
        { id: 'email', name: 'email', type: 'email_address', nullable: false, unique: true },
        { id: 'created_at', name: 'created_at', type: 'timestamptz', nullable: false, defaultValue: 'now()' },
      ],
      indexes: [{ id: 'email_lookup', name: 'users_email_idx', columnIds: ['email'], unique: true }],
    },
    {
      id: 'orders',
      schemaId: 'public',
      name: 'orders',
      kind: 'txn',
      description: 'Purchases created by users',
      columns: [
        { id: 'id', name: 'id', type: 'uuid', primaryKey: true },
        {
          id: 'order_number',
          name: 'order_number',
          type: 'bigint',
          nullable: false,
          unique: true,
          defaultValue: "nextval('public.order_number_seq')",
        },
        { id: 'user_id', name: 'user_id', type: 'uuid', nullable: false },
        { id: 'status', name: 'status', type: 'order_status', nullable: false, defaultValue: "'pending'" },
        { id: 'total_cents', name: 'total_cents', type: 'integer', nullable: false },
        { id: 'updated_at', name: 'updated_at', type: 'timestamptz', nullable: false, defaultValue: 'now()' },
      ],
      checks: [{ id: 'positive_total', expression: 'total_cents >= 0' }],
      indexes: [{ id: 'user_lookup', name: 'orders_user_id_idx', columnIds: ['user_id'] }],
    },
    {
      id: 'order-items',
      schemaId: 'public',
      name: 'order_items',
      kind: 'txn',
      description: 'Line items for each order',
      columns: [
        { id: 'id', name: 'id', type: 'uuid', primaryKey: true },
        { id: 'order_id', name: 'order_id', type: 'uuid', nullable: false },
        { id: 'sku', name: 'sku', type: 'text', nullable: false },
        { id: 'quantity', name: 'quantity', type: 'integer', nullable: false, defaultValue: '1' },
      ],
      indexes: [{ id: 'order_lookup', name: 'order_items_order_id_idx', columnIds: ['order_id'] }],
    },
  ],
  views: [
    {
      id: 'order-summary',
      schemaId: 'public',
      name: 'order_summary',
      columns: [
        { id: 'order_id', name: 'order_id', type: 'uuid' },
        { id: 'customer_email', name: 'customer_email', type: 'email_address' },
        { id: 'total_cents', name: 'total_cents', type: 'integer' },
      ],
      definition:
        'SELECT o.id AS order_id, u.email AS customer_email, o.total_cents FROM public.orders o JOIN public.users u ON u.id = o.user_id',
    },
    {
      id: 'customer-order-metrics',
      schemaId: 'public',
      name: 'customer_order_metrics',
      kind: 'materialized-view',
      columns: [
        { id: 'user_id', name: 'user_id', type: 'uuid' },
        { id: 'order_count', name: 'order_count', type: 'bigint' },
      ],
      definition: 'SELECT user_id, count(*) AS order_count FROM public.orders GROUP BY user_id',
    },
  ],
  sequences: [
    {
      id: 'order-number-seq',
      schemaId: 'public',
      name: 'order_number_seq',
      type: 'bigint',
      startWith: 1000,
      incrementBy: 1,
      ownedBy: { tableId: 'orders', columnId: 'order_number' },
    },
  ],
  functions: [
    {
      id: 'touch-updated-at',
      schemaId: 'public',
      name: 'touch_updated_at',
      returns: 'trigger',
      language: 'plpgsql',
      volatility: 'volatile',
      body: 'BEGIN\n  NEW.updated_at = now();\n  RETURN NEW;\nEND;',
    },
  ],
  triggers: [
    {
      id: 'orders-touch-updated-at',
      tableId: 'orders',
      name: 'orders_touch_updated_at',
      timing: 'before',
      events: ['update'],
      functionId: 'touch-updated-at',
      forEach: 'row',
    },
  ],
  policies: [
    {
      id: 'orders-tenant-policy',
      tableId: 'orders',
      name: 'orders_tenant_policy',
      command: 'select',
      roles: ['app_user'],
      using: "current_setting('app.user_id', true)::uuid = user_id",
    },
  ],
  relationships: [
    {
      id: 'orders-user',
      name: 'orders_user_id_fkey',
      sourceTableId: 'orders',
      sourceColumnIds: ['user_id'],
      targetTableId: 'users',
      targetColumnIds: ['id'],
      cardinality: 'many-to-one',
      onDelete: 'cascade',
    },
    {
      id: 'order-items-order',
      name: 'order_items_order_id_fkey',
      sourceTableId: 'order-items',
      sourceColumnIds: ['order_id'],
      targetTableId: 'orders',
      targetColumnIds: ['id'],
      cardinality: 'many-to-one',
      onDelete: 'cascade',
    },
  ],
  layout: {
    nodes: {
      'db-table:users': { x: 80, y: 80 },
      'db-table:orders': { x: 420, y: 120 },
      'db-table:order-items': { x: 760, y: 160 },
      'db-view:order-summary': { x: 760, y: 420 },
      'db-view:customer-order-metrics': { x: 1080, y: 420 },
      'db-enum:order-status': { x: 80, y: 390 },
      'db-domain:email-address': { x: 80, y: 560 },
      'db-sequence:order-number-seq': { x: 420, y: 390 },
      'db-function:touch-updated-at': { x: 420, y: 560 },
    },
  },
}
