import { globalStyle } from '@vanilla-extract/css'

globalStyle(':root, .af-themes', {
  vars: {
    '--font-size-xs': 'calc(12px * var(--scaling))',
    '--font-size-sm': 'calc(14px * var(--scaling))',
    '--font-size-md': 'calc(16px * var(--scaling))',
    '--font-size-lg': 'calc(18px * var(--scaling))',
    '--font-size-xl': 'calc(20px * var(--scaling))',
    '--font-size-2x': 'calc(24px * var(--scaling))',
    '--font-size-3x': 'calc(28px * var(--scaling))',
    '--font-size-4x': 'calc(34px * var(--scaling))',
    '--font-size-5x': 'calc(48px * var(--scaling))',
    '--font-weight-light': '300',
    '--font-weight-regular': '400',
    '--font-weight-medium': '500',
    '--font-weight-bold': '700',
    '--line-height-xs': 'calc(16px * var(--scaling))',
    '--line-height-sm': 'calc(20px * var(--scaling))',
    '--line-height-md': 'calc(24px * var(--scaling))',
    '--line-height-lg': 'calc(26px * var(--scaling))',
    '--line-height-xl': 'calc(28px * var(--scaling))',
    '--line-height-2x': 'calc(30px * var(--scaling))',
    '--line-height-3x': 'calc(36px * var(--scaling))',
    '--line-height-4x': 'calc(40px * var(--scaling))',
    '--line-height-5x': 'calc(56px * var(--scaling))',
    '--letter-spacing-xs': '0.0025em',
    '--letter-spacing-sm': '0em',
    '--letter-spacing-md': '0em',
    '--letter-spacing-lg': '-0.0025em',
    '--letter-spacing-xl': '-0.005em',
    '--letter-spacing-2x': '-0.00625em',
    '--letter-spacing-3x': '-0.0075em',
    '--letter-spacing-4x': '-0.01em',
    '--letter-spacing-5x': '-0.025em',
    '--default-font-family': 'var(--font-sans, ui-sans-serif, system-ui, sans-serif)',
    '--default-font-size': 'var(--font-size-md)',
    '--default-font-style': 'normal',
    '--default-font-weight': 'var(--font-weight-regular)',
    '--default-line-height': '1.5',
    '--default-letter-spacing': '0em',
    '--default-leading-trim-start': '0.42em',
    '--default-leading-trim-end': '0.36em',
    '--heading-font-family': 'var(--font-serif, var(--default-font-family))',
    '--heading-font-size-adjust': '1',
    '--heading-font-style': 'normal',
    '--heading-leading-trim-start': 'var(--default-leading-trim-start)',
    '--heading-leading-trim-end': 'var(--default-leading-trim-end)',
    '--heading-letter-spacing': '0em',
    '--heading-line-height-xs': 'calc(16px * var(--scaling))',
    '--heading-line-height-sm': 'calc(18px * var(--scaling))',
    '--heading-line-height-md': 'calc(22px * var(--scaling))',
    '--heading-line-height-lg': 'calc(24px * var(--scaling))',
    '--heading-line-height-xl': 'calc(26px * var(--scaling))',
    '--heading-line-height-2x': 'calc(30px * var(--scaling))',
    '--heading-line-height-3x': 'calc(36px * var(--scaling))',
    '--heading-line-height-4x': 'calc(40px * var(--scaling))',
    '--heading-line-height-5x': 'calc(56px * var(--scaling))',
    '--code-font-family': 'var(--font-mono, var(--font-geist-mono, ui-monospace, monospace))',
    '--code-font-size-adjust': '0.95',
    '--code-font-style': 'normal',
    '--code-font-weight': 'inherit',
    '--code-letter-spacing': '-0.007em',
    '--code-padding-top': '0.1em',
    '--code-padding-bottom': '0.1em',
    '--code-padding-left': '0.25em',
    '--code-padding-right': '0.25em',
    '--strong-font-family': 'var(--default-font-family)',
    '--strong-font-size-adjust': '1',
    '--strong-font-style': 'inherit',
    '--strong-font-weight': 'var(--font-weight-bold)',
    '--strong-letter-spacing': '0em',
    '--em-font-family': '"Times New Roman", "Times", serif',
    '--em-font-size-adjust': '1.18',
    '--em-font-style': 'italic',
    '--em-font-weight': 'inherit',
    '--em-letter-spacing': '-0.025em',
    '--quote-font-family': '"Times New Roman", "Times", serif',
    '--quote-font-size-adjust': '1.18',
    '--quote-font-style': 'italic',
    '--quote-font-weight': 'inherit',
    '--quote-letter-spacing': '-0.025em',
    '--tab-active-letter-spacing': '-0.01em',
    '--tab-active-word-spacing': '0em',
    '--tab-inactive-letter-spacing': '0em',
    '--tab-inactive-word-spacing': '0em',
  } as Record<string, string>,
  overflowWrap: 'break-word',
  fontFamily: 'var(--default-font-family)',
  fontSize: 'var(--default-font-size)',
  fontWeight: 'var(--default-font-weight)',
  fontStyle: 'var(--default-font-style)',
  lineHeight: 'var(--default-line-height)',
  letterSpacing: 'var(--default-letter-spacing)',
  WebkitFontSmoothing: 'antialiased',
  MozOsxFontSmoothing: 'grayscale',
})
