import type { FileManagerFile, FileManagerFolder } from './types'

export const sampleFileManagerFolders: FileManagerFolder[] = [
  { id: 'design', name: 'Design', parentId: null, sizeLabel: '5.8 GB' },
  { id: 'projects', name: 'Projects', parentId: null, sizeLabel: '3.2 GB' },
  { id: 'projects-01', name: 'Projects_01', parentId: 'projects' },
  { id: 'projects-02', name: 'Projects_02', parentId: 'projects' },
  { id: 'projects-03', name: 'Projects_03', parentId: 'projects' },
  { id: 'projects-04', name: 'Projects_04', parentId: 'projects' },
  { id: 'music', name: 'Music', parentId: null, sizeLabel: '1.5 GB' },
  { id: 'pictures', name: 'Pictures', parentId: null, sizeLabel: '1.7 GB' },
  { id: 'documents', name: 'Documents', parentId: null, sizeLabel: '440 MB' },
  { id: 'downloads', name: 'Downloads', parentId: null, sizeLabel: '10.1 GB' },
]

export const sampleFileManagerFiles: FileManagerFile[] = [
  {
    id: 'brand-assets',
    name: 'Brand assets',
    type: 'folder',
    folderId: 'projects',
    sizeLabel: '2.4 GB',
    modifiedLabel: 'Today',
  },
  {
    id: 'campaign-images',
    name: 'Campaign images',
    type: 'folder',
    folderId: 'projects',
    sizeLabel: '1.8 GB',
    modifiedLabel: 'Yesterday',
  },
  {
    id: 'product-shots',
    name: 'Product shots',
    type: 'folder',
    folderId: 'projects',
    sizeLabel: '4.2 GB',
    modifiedLabel: 'Apr 18',
  },
  {
    id: 'launch-plan',
    name: 'Launch plan.pdf',
    type: 'document',
    folderId: 'projects',
    sizeLabel: '18 MB',
    modifiedLabel: 'Apr 16',
  },
  {
    id: 'hero-image',
    name: 'Hero image.png',
    type: 'image',
    folderId: 'projects',
    sizeLabel: '12 MB',
    modifiedLabel: 'Apr 14',
  },
  {
    id: 'voiceover',
    name: 'Voiceover.mp3',
    type: 'audio',
    folderId: 'projects',
    sizeLabel: '84 MB',
    modifiedLabel: 'Apr 12',
  },

  {
    id: 'hero-image1',
    name: 'Hero image.png',
    type: 'image',
    folderId: 'projects',
    sizeLabel: '12 MB',
    modifiedLabel: 'Apr 14',
  },
  {
    id: 'voiceover1',
    name: 'Voiceover.mp3',
    type: 'audio',
    folderId: 'projects',
    sizeLabel: '84 MB',
    modifiedLabel: 'Apr 12',
  },

  {
    id: 'launch-plan1',
    name: 'Launch plan.pdf',
    type: 'document',
    folderId: 'projects',
    sizeLabel: '18 MB',
    modifiedLabel: 'Apr 16',
  },

  {
    id: 'brand-assets2',
    name: 'Brand assets',
    type: 'folder',
    folderId: 'projects',
    sizeLabel: '2.4 GB',
    modifiedLabel: 'Today',
  },
  {
    id: 'campaign-images2',
    name: 'Campaign images',
    type: 'folder',
    folderId: 'projects',
    sizeLabel: '1.8 GB',
    modifiedLabel: 'Yesterday',
  },
  {
    id: 'product-shots2',
    name: 'Product shots',
    type: 'folder',
    folderId: 'projects',
    sizeLabel: '4.2 GB',
    modifiedLabel: 'Apr 18',
  },
  {
    id: 'launch-plan2',
    name: 'Launch plan.pdf',
    type: 'document',
    folderId: 'projects',
    sizeLabel: '18 MB',
    modifiedLabel: 'Apr 16',
  },
  {
    id: 'hero-image2',
    name: 'Hero image.png',
    type: 'image',
    folderId: 'projects',
    sizeLabel: '12 MB',
    modifiedLabel: 'Apr 14',
  },
  {
    id: 'voiceover3',
    name: 'Voiceover.mp3',
    type: 'audio',
    folderId: 'projects',
    sizeLabel: '84 MB',
    modifiedLabel: 'Apr 12',
  },

  {
    id: 'hero-image12',
    name: 'Hero image.png',
    type: 'image',
    folderId: 'projects',
    sizeLabel: '12 MB',
    modifiedLabel: 'Apr 14',
  },
  {
    id: 'voiceover2',
    name: 'Voiceover.mp3',
    type: 'audio',
    folderId: 'projects',
    sizeLabel: '84 MB',
    modifiedLabel: 'Apr 12',
  },

  {
    id: 'launch-plan3',
    name: 'Launch plan.pdf',
    type: 'document',
    folderId: 'projects',
    sizeLabel: '18 MB',
    modifiedLabel: 'Apr 16',
  },
]
