import { baseUnoConfig } from '@incmix/config/uno.config'
import { defineConfig } from 'unocss'

export default defineConfig({
  ...baseUnoConfig,
  content: {
    filesystem: ['./src/**/*.{js,ts,jsx,tsx,mdx}', './docs/**/*.{js,ts,jsx,tsx,mdx}'],
  },
  theme: {
    ...baseUnoConfig.theme,
  },
  safelist: [
    ...(baseUnoConfig.safelist ?? []),
    // Avatar sizes
    'w-[1.5rem]',
    'h-[1.5rem]',
    'w-[1.75rem]',
    'h-[1.75rem]',
    'w-[2rem]',
    'h-[2rem]',
    'w-[2.5rem]',
    'h-[2.5rem]',
    'w-[2.75rem]',
    'h-[2.75rem]',
    'w-[5rem]',
    'h-[5rem]',
    'text-xs',
    'text-sm',
    'text-base',
    'text-lg',
    'text-xl',
    'text-2xl',
    'leading-4',
    'leading-5',
    'leading-6',
    'leading-[1.625rem]',
    'leading-7',
    'leading-[1.875rem]',
    // Avatar presence
    'w-[0.375rem]',
    'h-[0.375rem]',
    'w-[0.5rem]',
    'h-[0.5rem]',
    'w-[0.625rem]',
    'h-[0.625rem]',
    'w-[0.75rem]',
    'h-[0.75rem]',
    'w-[0.875rem]',
    'h-[0.875rem]',
    'w-[1rem]',
    'h-[1rem]',
    // Avatar busy lines
    'w-[0.5rem]',
    'w-[0.625rem]',
    'w-[0.75rem]',
    'w-[0.875rem]',
    'w-[1rem]',
    'w-[1.125rem]',
  ],
})
