import type { ElementDocsNavItem } from './element-docs-types'

export const elementDocsNav: ElementDocsNavItem[] = [
  { slug: 'accordion', title: 'Accordion' },
  { slug: 'alert-dialog', title: 'Alert Dialog' },
  { slug: 'avatar', title: 'Avatar' },
  { slug: 'avatar-group', title: 'Avatar Group' },
  { slug: 'avatar-pie', title: 'Avatar Pie' },
  { slug: 'badge', title: 'Badge' },
  { slug: 'button', title: 'Button' },
  { slug: 'callout', title: 'Callout' },
  { slug: 'card', title: 'Card' },
  { slug: 'context-menu', title: 'Context Menu' },
  { slug: 'data-list', title: 'Data List' },
  { slug: 'dialog', title: 'Dialog' },
  { slug: 'dropdown-menu', title: 'Dropdown Menu' },
  { slug: 'image', title: 'Image' },
  { slug: 'icon-button', title: 'Icon Button' },
  { slug: 'popover', title: 'Popover' },
  { slug: 'scroll-area', title: 'Scroll Area' },
  { slug: 'segmented-control', title: 'Segmented Control' },
  { slug: 'slider', title: 'Slider' },
  { slug: 'spinner', title: 'Spinner' },
  { slug: 'table', title: 'Table' },
  { slug: 'tabs', title: 'Tabs' },
  { slug: 'timeline', title: 'Timeline' },
  { slug: 'toast', title: 'Toast' },
]
