'use client'

export {
  areLayoutItemsEqual,
  clamp,
  createDashboardItemsFromPreset,
  createDashboardItemsFromPresetForColumns,
  createDashboardLayoutsFromPreset,
  createDashboardPresetFromItems,
  type DashboardBreakpointConfig,
  type DashboardColumnConfig,
  DashboardLayout as Dashboard,
  DashboardLayout,
  type DashboardLayoutBreakpoint,
  type DashboardLayoutChangeDetails,
  type DashboardLayoutItem,
  type DashboardLayoutMode,
  DashboardLayoutModeControl,
  type DashboardLayoutModeControlProps,
  type DashboardLayoutPacking,
  type DashboardLayoutPreset,
  type DashboardLayoutProps,
  type DashboardLayoutRenderState,
  type DashboardPresetFromItemsOptions,
  type DashboardPresetLayoutOptions,
  DashboardPresetPicker,
  type DashboardPresetPickerProps,
  DashboardPresetPreview,
  type DashboardPresetPreviewProps,
  type DashboardResizeHandle,
  type DashboardResolvedResizeHandle,
  type DashboardResponsiveLayoutItems,
  type DashboardResponsiveLayoutOptions,
  dashboardLayoutBreakpoints,
  dashboardLayoutPresets,
  getDashboardBreakpointForWidth,
  getDashboardColumnsForBreakpoint,
  getDashboardColumnsForWidth,
  getDashboardLayoutBreakpoint,
  getGridHeight,
  getItemLabel,
  isDashboardLayoutPresetDirty,
  normalizeDashboardLayoutItem,
  normalizeDashboardLayoutItems,
  normalizeDashboardResponsiveLayouts,
  packDashboardLayoutItems,
  packDashboardLayoutItemsWithPinned,
  updateDashboardLayoutsWithItems,
  useElementWidth,
} from './DashboardLayout'
export {
  type DashboardRglBreakpoint,
  type DashboardRglBreakpoints,
  type DashboardRglCols,
  type DashboardRglLayoutItem,
  type DashboardRglLayouts,
  type DashboardRglMigrationOptions,
  type DashboardRglResizeHandle,
  dashboardBreakpointsFromRglBreakpoints,
  dashboardColumnsFromRglCols,
  dashboardLayoutItemFromRglItem,
  dashboardLayoutItemsFromRglLayout,
  dashboardLayoutItemsFromRglLayouts,
  dashboardResponsiveLayoutItemsFromRglLayouts,
  dashboardRglDefaultBreakpoints,
  dashboardRglDefaultCols,
  getDashboardBreakpointFromRglBreakpoint,
  getDashboardRglBreakpointForWidth,
  getDashboardRglLayoutBreakpoint,
  rglLayoutFromDashboardItems,
  rglLayoutItemFromDashboardItem,
  updateRglLayoutsWithDashboardItems,
} from './rgl-migration'
